stages:
  - setup
  - test

setup:docker:linux:
  image: docker:18.09.0
  stage: setup
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_NAME_CI: ${CI_REGISTRY_IMAGE}/puma-ci-linux:${CI_COMMIT_REF_SLUG}
  services:
    - docker:dind
  script:
    # Login to our registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin ${CI_REGISTRY}
    - cd ./ci/docker/linux
    - docker build --target PUMA_CI_LINUX -t ${DOCKER_IMAGE_NAME_CI} .
    - docker push ${DOCKER_IMAGE_NAME_CI}
  tags:
    - docker
    - gce
  only:
    changes:
      - ci/docker/linux/**/*

.test_base_task: &test_base_task
  script:
    - pytest

test:windows:
  <<: *test_base_task
  tags:
    - gift-hopper
    - windows
  # This section should ideally be identical to the Linux section. However, we can't yet use Docker
  # on the Hopper Windows version (1903) due to https://gitlab.com/gitlab-org/gitlab-runner/issues/4396
  variables:
    WORKON_HOME: /c/Users/Public/PythonVirtualEnvs
    VIRTUAL_ENV_NAME: xononav-ci-${CI_JOB_ID}
  before_script:
    # Create and activate virtual environment
    - mkvirtualenv.bat --python=python3.7.1.exe ${VIRTUAL_ENV_NAME}
    - source ${WORKON_HOME}/${VIRTUAL_ENV_NAME}/Scripts/activate
  after_script:
    # Cleanup virtual environment
    - rmvirtualenv.bat ${VIRTUAL_ENV_NAME}

test:linux:
  <<: *test_base_task
  image: ${CI_REGISTRY_IMAGE}/puma-ci-linux:${CI_COMMIT_REF_SLUG}
  tags:
    - gift-little
    - docker
